### ISSUE TITLE
Review: new figure

### ISSUE THREAD

**Issue by jensroes** [jensroes/prowrite-mixture-models#14]
[posteriorplot.pdf](https://github.com/user-attachments/files/17475031/posteriorplot.pdf)

I do think this is much better :)

**Comment by RConijn** [comment]
agreed - maybe it's just me but I'd expect before sentence to be on top though

**Comment by jensroes** [comment]
Agreed

**Comment by Mark-Torrance** [comment]
This is good :)

**Comment by Mark-Torrance** [comment]
Minor thing, but I would give both time scales in ms (so not seconds slow down).
More major thing: I think framing this as slow down is problematic. I know that this comes form that fact that the model estimates beta and delta, rather than beta1 and beta2. But conceptually there is not "slow down". We've put quite a bit of effort into explaining that the second distribution isn't derived from the first. It's not the first distribution with a delay added on. It results from a completely different process.

My preference would be just to give the estimated central tendency of the second distribution. I know that that's exactly what we show in figure 1. But I think conceptually that's the right framing, and also the right thing to be reporting. There is no reason for readers to be thinking "how much slower compared to motor planning for this group is the second distribution". There's not reason to compare with motor planning at all.

**Comment by jensroes** [comment]
Okay this makes sense now cause we got entirely rid off the unconstrained model.

**Comment by jensroes** [comment]
[posteriorplot.pdf](https://github.com/user-attachments/files/17488050/posteriorplot.pdf)

Just an update. I'm happy with this.

**Comment by RConijn** [comment]
maybe add labels to the x-axis?:)

**Comment by jensroes** [comment]
there is one. I think ithe upload didn't really work. try again:

[posteriorplot.pdf](https://github.com/user-attachments/files/17488398/posteriorplot.pdf)

**Comment by RConijn** [comment]
Oh is just meant adding (ms)

**Comment by jensroes** [comment]
ah okay, no cause the right panel isn't msecs and the caption (which you can't know) is clarifying this.
